version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test 
 development-deploy:
    machine:
      enabled: true
        steps:
         -add_ssh_keys:
          fingerprints: 
           -"9e:3c:6b:62:fc:60:5c:71:65:c3:7e:3b:8b:1a:8c:48"
        - run:
            command:
              ssh ubuntu@18.234.219.63 "bash deploy.sh"
 
 approval-job:
    
    production-deploy:
      machine:
        enabled: true
    steps:  
     - add_ssg_keys:
           fingerprints:
             - "9e:3c:6b:62:fc:60:5c:71:65:c3:7e:3b:8b:1a:8c:48"
      - run:
          command:
            ssh ubuntu@3.90.218.59 "bash deploy.sh"

workflows:
    build-and-test:
       jobs: 
      - test: 
         filters: 
           branches: 
             only: master 
      - development-deploy:
             requires:
                 -test 
                  filters:
                    branches: 
                      only: master 
      - approval-job:
       type: approval
       requires: 
          - development-deploy
           filters:
             branches: 
               only: master 
     - production-deploy:
         requires: 
           - approval-job
            filters:
              branches:
                only: master